parameters:
    percona_launchpad_bugs_stats_engine.launchpad_api.class: Percona\LaunchpadBugsStats\EngineBundle\Services\LaunchpadApi\LaunchpadApi

services:
    percona.launchpad:
        class: %percona_launchpad_bugs_stats_engine.launchpad_api.class%
        arguments: [@liip_doctrine_cache.ns.launchpad]
        calls:
            - [ setLogger, [@logger] ]